/* tslint:disable */
// @ts-nocheck
const { writeFile } = require('fs');

// read environment variables from .env file
require('dotenv').config();

const targetPath = `./src/environments/environment.ts`;

// we have access to our environment variables
// in the process.env object thanks to dotenv
const environmentFileContent = `

// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

export const environment = {
  production: true,
  API_URL: "${process.env.API_URL}",
  apiKey: "${process.env.apiKey}",
  authDomain: "${process.env.authDomain}",
  projectId: "${process.env.projectId}",
  storageBucket: "${process.env.storageBucket}",
  messagingSenderId: "${process.env.messagingSenderId}",
  appId: "${process.env.appId}"
};
`;

// write the content to the respective file
writeFile(targetPath, environmentFileContent, function (err: any) {

  if (err) {
    console.log(err);
  }

  console.log(`Wrote variables to ${targetPath}`);

});

/* tslint:enable */
